---
title: "20221214_MIC_MBC_oxygen"
output: html_document
date: '2022-12-14'
---

```{r setup, echo =FALSE}

.libPaths('C:\\Users\\zuendj\\Documents\\R4Libs')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/zuendj/Desktop/03_data R", cho = TRUE, warning = FALSE, message = FALSE)
# library(knitr)
# Install Packages:
# install.packages("rlang")
# install.packages("tidyr")
# install.packages("ggbreak")
# unload("dplyr")
# unload("mia")
library(tidyverse)
# library(ggplot2)
# library(tidyr)
# install.packages("devtools")
# devtools::install_github("slowkow/ggrepel")
# library(ggrepel)
# library(ggbreak)
 library(openxlsx)
 library(rstatix)
```

##Load the Data
```{r}
bacteria_MIC <- list.files(path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/input/h2o2/MIC")
bacteria_MBC <- list.files(path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/input/h2o2/MBC")
#bacteria<- bacteria[-(27:29)]


options(scipen=999)


#define empty matrices, no values added so far 
MIC_average<- matrix(0, length(bacteria_MIC), 13)
MBC_average<- matrix(0, length(bacteria_MBC), 13)

blank_corrected_MIC<- matrix(0, length(bacteria_MIC)*6, 13)
blank_corrected_MBC<- matrix(0, length(bacteria_MBC)*6, 13)

#define MIC and MBC value for each species 
#MIC, fill values into MIC, here OD corrected values, but not corrected with agar 
row = 0

setwd("C:/Users/zuendj/Desktop/03_data R/oxidative stress/input/h2o2/MIC")
for (l in 1:length(bacteria_MIC)) {
  #generate MICwide format
  MICwide = read.csv(bacteria_MIC[l], sep=";", header=F, check.names =F)
  #look for A indicating the area in the excel file with the data
  for (r in 1:40) {
    if (MICwide[r,1]=="A") {
      zeile = r
    }
  }
#########################################
  # print(bacteria_MIC[l])
  row = (l-1)*6
  # print(row)

  #generate blank corrected values
  for(i in 1:12) {
    #x indicated the colum->'A' is in column 1 and the data next to it from column 2 on
    x = 1+i
    zeile_end = zeile+6
    d = as.numeric(unlist(data.frame(MICwide[zeile:zeile_end, x])))
    for(j in 1:6){
      y = d[j] - d[7]
      blank_corrected_MIC[row+j, i] = y
    }
  }
  
  
  
  #########################################
  #generate averages 
  for(i in 1:12) {
    r1= row+1
    r2= row+6
    MIC_average[l, i] = as.numeric(mean(blank_corrected_MIC[r1:r2, i],  na.rm=TRUE))
  }
} 




#MBC
setwd( "C:/Users/zuendj/Desktop/03_data R/oxidative stress/input/h2o2/MBC")
row = 0
for (l in 1:length(bacteria_MBC)) {
  #generate MICwide format
  MBCwide = read.csv(bacteria_MBC[l], sep=";", header=F, check.names =F)
  #look for A indicating the area in the excel file with the data
  for (r in 1:40) {
    if (MBCwide[r,1]=="A") {
      zeile = r
    }
  }
  #########################################
  # print(bacteria_MBC[l])
  row = (l-1)*6
  # print(row)
  
  #generate blank corrected values
  for(i in 1:12) {
    #x indicated the colum->'A' is in column 1 and the data next to it from column 2 on
    x = 1+i
    zeile_end = zeile+6
    d = as.numeric(unlist(data.frame(MBCwide[zeile:zeile_end, x])))
    for(j in 1:6){
      y = d[j] - d[7]
      blank_corrected_MBC[row+j, i] = y
    }
  }
  
  #########################################
  #generate averages 
  for(i in 1:12) {
    r1= row+1
    r2= row+6
    MBC_average[l, i] = as.numeric(mean(blank_corrected_MBC[r1:r2, i],  na.rm=TRUE))
  }
} 

```


## Get the MIC for individual repleciates
```{r}
#########################################
#define row names for the blank corrected 
bacteria <- strsplit(bacteria_MBC, ".csv")
bacteria <- as.character(bacteria)

row_names_mbc<-matrix(0,length(bacteria)*6,1)
position = 0
for (i in 1:length(bacteria)) {
  for (j in 1:6) {
    row_names_mbc[position+j,1] = bacteria[i]
  }
  position = position+6
}


bacteria <- strsplit(bacteria_MIC, ".csv")
bacteria <- as.character(bacteria)

row_names_mic<-matrix(0,length(bacteria)*6,1)
position = 0
for (i in 1:length(bacteria)) {
  for (j in 1:6) {
    row_names_mic[position+j,1] = bacteria[i]
  }
  position = position+6
}


MIC_replicates_h2o2 <-data.frame(row_names_mic, blank_corrected_MIC)
colnames(MIC_replicates_h2o2)<-list("bacteria", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13")

MBC_replicates_h2o2 <-data.frame(row_names_mbc, blank_corrected_MBC)
colnames(MBC_replicates_h2o2)<-list("bacteria","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13")
```

```{r}
write.xlsx(MBC_replicates_h2o2, file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MBC_H2O2_replicates.xlsx")
write.xlsx(MIC_replicates_h2o2, file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_H2O2_replicates.xlsx")


# 
# MIC_replicates_h2o2[c(24, 161, 81),c("7268")]<-0
# MIC_replicates_h2o2[c(81),c("2271.25")]<-0
# 
# MBC_replicates_h2o2[c(69, 161, 162),c("2271.25")]<-0
# MBC_replicates_h2o2[c(171),c("7268")]<-0




MBC_mod<-read.xlsx("C:/Users/zuendj/Desktop/03_data R/oxidative stress/MBC_H2O2_replicates_non_mod.xlsx")
# MBC_mod[is.na(MBC_mod)] <- 0
MIC_mod<-read.xlsx("C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_H2O2_replicates_non_mod.xlsx")
# MIC_mod[is.na(MIC_mod)] <- 0
```
##Outlier detection
```{r}
calculate_iqr <- function(x) {
  q3 <- quantile(x, 0.75 , na.rm =TRUE)
  q1 <- quantile(x, 0.25, na.rm =TRUE)
  iqr_value <- q3 - q1
  return(iqr_value)}
q3_calc <- function(x) {
  q3 <- quantile(x, 0.75, na.rm =TRUE)
  return(q3)}

q1_calc <- function(x) {
  q1 <- quantile(x, 0.25, na.rm =TRUE)
  return(q1)}

z=1.5

#####MBC

MBC_mod%>%
  gather(condition, value, `1`: `12`)->MBC_H2O2_replicates_long



left_join(MBC_H2O2_replicates_long, setNames(aggregate(MBC_H2O2_replicates_long$value, by=list(MBC_H2O2_replicates_long$bacteria, MBC_H2O2_replicates_long$condition), FUN=calculate_iqr), c("bacteria", "condition","IQR")))%>%
  left_join(., setNames(aggregate(MBC_H2O2_replicates_long$value, by=list(MBC_H2O2_replicates_long$bacteria, MBC_H2O2_replicates_long$condition), FUN=q3_calc), c("bacteria", "condition","Q3")))%>%
  left_join(., setNames(aggregate(MBC_H2O2_replicates_long$value, by=list(MBC_H2O2_replicates_long$bacteria, MBC_H2O2_replicates_long$condition), FUN=q1_calc), c("bacteria", "condition","Q1")))%>%
mutate(value = ifelse(value - (Q1 - (z*IQR)) < 0, NA, value))%>% #lowerbound
  mutate(value = ifelse((Q3 + (z*IQR))- value < 0, NA, value))-> outlier_corr

outlier_corr[, c("bacteria", "condition", "value", "replicate","technical_rep")]%>%
  pivot_wider(values_from = value, names_from = condition)->MBC_H2O2_replicates_outlier_corr

#######MIC

MIC_mod%>%
  gather(condition, value, `1`: `12`)->MIC_H2O2_replicates_long

left_join(MIC_H2O2_replicates_long, setNames(aggregate(MIC_H2O2_replicates_long$value, by=list(MIC_H2O2_replicates_long$bacteria, MIC_H2O2_replicates_long$condition), FUN=calculate_iqr), c("bacteria", "condition","IQR")))%>%
  left_join(., setNames(aggregate(MIC_H2O2_replicates_long$value, by=list(MIC_H2O2_replicates_long$bacteria, MIC_H2O2_replicates_long$condition), FUN=q3_calc), c("bacteria", "condition","Q3")))%>%
  left_join(., setNames(aggregate(MIC_H2O2_replicates_long$value, by=list(MIC_H2O2_replicates_long$bacteria, MIC_H2O2_replicates_long$condition), FUN=q1_calc), c("bacteria", "condition","Q1")))%>%
mutate(value = ifelse(value - (Q1 - (z*IQR)) < 0, NA, value))%>% #lowerbound
  mutate(value = ifelse((Q3 + (z*IQR))- value < 0, NA, value)) -> outlier_corr

outlier_corr[, c("bacteria", "condition", "value", "replicate","technical_rep")]%>%
  pivot_wider(values_from = value, names_from = condition)->MIC_H2O2_replicates_outlier_corr
  
  

```

## Define the MIC/MBC values

```{r}
## GET AVERAGE OF TECHNICAL REPLICATES ##
#get long format
average_long<-gather(MIC_H2O2_replicates_outlier_corr, condition, OD, "1":"12", factor_key = T )
#take averages of the technical replicate
average_long_tec<-setNames(aggregate(average_long$OD, list(average_long$bacteria, average_long$replicate, average_long$condition), FUN=mean, na.rm=TRUE), c("bacteria",  "replicate","condition", "OD"))

#get average per condition -> to get max
average<-setNames(aggregate(average_long_tec$OD, list(average_long_tec$bacteria, average_long_tec$condition), FUN=mean, na.rm=TRUE), c("bacteria", "condition" ,"OD"))
# find max
max_mic<-setNames(aggregate(average$OD, by = list(average$bacteria), max, na.rm=TRUE), c("bacteria", "max"))
#after getting the average per replicate, get wide table again
MIC_replicates_wide<-pivot_wider(average, names_from = condition , values_from = OD)


#same for MBC
average_long<-gather(MBC_H2O2_replicates_outlier_corr, condition, OD, "1":"12", factor_key = T )
average_long_tec<-setNames(aggregate(average_long$OD, list(average_long$bacteria, average_long$replicate, average_long$condition), FUN=mean, na.rm=TRUE), c("bacteria",  "replicate","condition", "OD"))
average<-setNames(aggregate(average_long_tec$OD, list(average_long_tec$bacteria, average_long_tec$condition), FUN=mean, na.rm=TRUE), c("bacteria", "condition" ,"OD"))
max_mbc<-setNames(aggregate(average$OD, by = list(average$bacteria), max, na.rm=TRUE), c("bacteria", "max"))
#after getting the average per replicate, get wide table again
MBC_replicates_wide<-pivot_wider(average, names_from = condition , values_from = OD)

# MIC_mod_av<-left_join(MIC_replicates_wide, max_mic)
# MBC_mod_av<-left_join(MBC_replicates_wide, max_mbc)
```

```{r}
# 
# MBC_mod_av%>%
#   subset(bacteria %in% "Bacteroides xylanisolvens")

## GET MIC - as a function of MAX ##
MIC_vector <- vector()
for (i in 1:nrow(MIC_replicates_wide)) { #vertical 
  candidates <- vector()
     for(j in 2:13) {#horizontal 
       if (!is.na(MIC_replicates_wide[i,j]) & MIC_replicates_wide[i,j]/MIC_replicates_wide[i, 2]>0.2 & MIC_replicates_wide[i,j]>0.0336) {#-> MIC_value_absolut)
         candidates <- append(candidates, colnames(MIC_replicates_wide)[j])
         candidates <-as.numeric(candidates)
         
       }
     }
  # print(max(candidates))
  MIC_vector <- append(MIC_vector, max(candidates))
}



MBC_vector <- vector()
for (i in 1:nrow(MBC_replicates_wide)) { #vertical 
  candidates <- vector()
  for(j in 2:13) {#horizontal 
    if (!is.na(MBC_replicates_wide[i,j]) & MBC_replicates_wide[i,j]/MBC_replicates_wide[i, 2]>0.2 & MBC_replicates_wide[i,j]>0.0336) {#-> MIC_value_absolut)
      
      candidates <- append(candidates, colnames(MBC_replicates_wide)[j])
      candidates <-as.numeric(candidates)
    }
  }
   # print(max(candidates))
  MBC_vector <- append(MBC_vector, max(candidates))
}



```

```{r}
#assign MIC/MBC vectors to a data frame
tolerances_h2o2 <- data.frame(bacteria = MBC_replicates_wide$bacteria,
                                  MIC = as.numeric(MIC_vector),
                                  MBC = as.numeric(MBC_vector)
                              )
```


## relative od values
```{r}
od_wide<-rbind(MBC_replicates_wide %>%
             mutate(assay="MBC"), 
           MIC_replicates_wide%>%
             mutate(assay="MIC"))
rel <- od_wide
for (i in 1:nrow(rel)) { #vertical
  for(j in 2:13) {#horizontal
     rel[i,j] = od_wide[i,j]/od_wide[i, 2]
  }}

rel_long<-gather(rel, condition, OD, "1":"12", factor_key = T)

```

```{r}

rel_long%>%
  left_join(., tolerances_h2o2%>%
              gather(assay, tolerance, "MIC", "MBC"))%>%
 mutate(bacteria = recode(bacteria, "Eubacterium eligens" = "Lachnospira eligens" ,
                             "Phocaeicola vulgatus" = "Bacteroides vulgatus",
                          "Lachnospira sp" = "Lachnospiraceae bacterium"))->rel_long
```

```{r}

rel_long%>%
  subset(!bacteria %in% c("Subdoligranulum variable", "Anaerobutyricum hallii", "Marvinbryantia formatixigens", "Ruminococcus bromii"))%>%
  mutate(OD = OD * 100)%>%
  mutate(bacteria = fct_reorder(bacteria, tolerance))%>%
   mutate(assay = ifelse(assay=="MIC", "a_MIC", assay))%>%
  mutate(condition = as.numeric(paste(condition)))%>% 
  mutate(OD = ifelse(OD < 0 , 0, OD))%>%
  mutate(OD = ifelse(OD > 120 , 120, OD))->sub

sub%>%
  ggplot(aes(x = condition, y = assay, fill = OD, pattern_type = condition)) + 
  labs(x=expression(paste(H[2]*O[2])))+
  theme(text = element_text(size=8), 
        axis.title.x = element_text(vjust=-0.8),
        axis.text.x = element_text(angle = 90, vjust= 0.5, hjust=1),
        axis.title.y= element_blank(),
        strip.text.y = element_text(angle=0,  hjust = 0, face="italic"),
        strip.background = element_blank(),
        axis.ticks.y = element_blank(),
        plot.title = element_text(hjust=0.25),
        panel.background = element_rect(fill="transparent"),
        panel.spacing = unit(0, "lines"))+
  scale_x_continuous(labels=c("0 nM", 
                              "6.4 nM",  
                              "21 nM", 
                              "66 nM", 
                              expression("2.2"~mu*M), 
                              expression("6.8"~mu*M),  
                              expression("21"~mu*M),
                              expression("69"~mu*M),
                              expression("222"~mu*M),
                              expression("710"~mu*M),  
                              "2.3 mM", "7.3 mM" ), 
                     breaks=c(1, 2, 3, 4, 5, 6, 7,  8 ,9 ,10, 11, 12))+

  ggtitle(expression(Growth~capability~upon~H[2]*O[2]-spike))+
     scale_y_discrete(labels = c('a_MIC' = 'Stress', 'MBC' = 'Post'), limits=rev)+
  
   new_scale_fill() +
  
   geom_raster(data = filter(sub, assay == "a_MIC"), aes(fill = OD)) +
  scale_fill_steps(
    breaks = c(  20,  40,  60,80,  100, 120),
    name = expression(OD~`[%]`),
    guide = guide_colorbar(title.position = "top", title.vjust = 0.5), low="#193854", high ="indianred" ) +
  
  new_scale_fill() +
 geom_raster(data = filter(sub, assay == "MBC"), aes(fill = OD)) +
  scale_fill_steps(
    breaks = c(  20,  40,  60,80,  100, 120),
    name = expression(OD~`[%]`),
    guide = guide_colorbar(title.position = "top", title.vjust = 0.5), low="#193854", high ="deepskyblue" ) +
  
  facet_grid(rows =vars( bacteria), scales = "free", space = "free")

# show(p + theme(legend.position = "none"))

ggsave(filename = "MIC_MBC_h2o2.png", 
       path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/output_reanalysis", 
       width =10,
       height = 18,
       units = c("cm")#, 
       #bg="transparent"
       )

# 
# show(p)
# 
# ggsave(filename = "legend.jpeg", 
#        path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/output_reanalysis", 
#        width = 14,
#        height = 27,
#        units = c("cm"))


```


```{r}

# tax%>%
#   subset(!bacteria %in% c("Subdoligranulum variable", "Anaerobutyricum hallii", "Marvinbryantia formatixigens", "Ruminococcus bromii"))%>%
#   drop_na(OD)%>%
#   mutate(assay = factor(assay, levels=c("MIC", "MBC")))%>%
#   subset(!condition %in% 13)%>%
#   mutate(OD = OD * 100)-> sub
# 
#   setNames(aggregate(sub$OD, by=list(sub$assay, sub$condition), FUN=mean), c("assay", "condition", "OD"))->sub
#   
#   
#   
#  sub%>%           
#   ggplot(aes(x = condition, y = assay, fill = OD)) + 
#   geom_raster() +
#   labs(x=expression(paste(H[2]*O[2])))+
#   theme(text = element_text(size=15), 
#         axis.title.x = element_text(size=20, vjust=-0.8),
#         axis.text.x = element_text(size=15, angle = 90, vjust= 0.5, hjust=1),
#         axis.title.y= element_blank(),
#         axis.text.y=element_text(size=15),
#         strip.text.y = element_text(angle=0, size=15, hjust = 0, face="italic"),
#         strip.background = element_blank(),
#         axis.ticks.y = element_blank(),
#         legend.text = element_text(size = 15),
#         legend.title = element_text(size= 15),
#         plot.title = element_text(size=20, hjust=0.25),
#         panel.background = element_rect(fill="transparent", colour=NA),
#         panel.border=element_rect(fill=NA),
#          plot.background = element_rect(fill='transparent', color=NA))+
#   scale_x_continuous(labels=c("0 nM", 
#                               "6.4 nM",  
#                               "21 nM", 
#                               "66 nM", 
#                               expression("2.2"~mu*M), 
#                               expression("6.8"~mu*M),  
#                               expression("21"~mu*M),
#                               expression("69"~mu*M),
#                               expression("222"~mu*M),
#                               expression("710"~mu*M),  
#                               "2.3 mM", "7.3 mM" ), 
#                      breaks=c(1, 2, 3, 4, 5, 6, 7,  8 ,9 ,10, 11, 12))+
#   labs(fill = expression(relative~OD[600]~'[%]'))+
#   scale_fill_steps(breaks = c(10,50,75))+
#   scale_y_discrete(labels = c('MIC' = 'Stress', 'MBC' = 'Post'), limits=rev)->p
# 
# show(p + theme(legend.position = "none"))
# 
# ggsave(filename = "MIC_MBC_h2o2_growth_only.png", 
#        path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/output_reanalysis", 
#        width =10,
#        height = 5,
#        units = c("cm"), 
#        bg="transparent")
# 
# 
# show(p)
# 
# ggsave(filename = "legend.jpeg", 
#        path = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/output_reanalysis", 
#        width = 10,
#        height = 5,
#        units = c("cm"))


```



```{r}
h2o2<-setNames(aggregate(hoi$value, by=list(hoi$bacteria, hoi$assay, hoi$replicate), FUN=mean), c("bacteria", "assay", "replicate", "value_H2O2"))
write.xlsx(h2o2, file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_MBC_H2O2.xlsx")
```

# Calculate Differences - MIC/MBC
```{r}
h2o2_wide<-pivot_wider(h2o2, names_from = assay, values_from= value_H2O2)
h2o2_wide$diff <- h2o2_wide$MBC - h2o2_wide$MIC
write.xlsx(h2o2_wide, file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_MBC_h2O2_difference.xlsx")
```

## Trial sig. testing

```{r}
# i=1
# j=4
# 
# bact<-(unique(MIC_mod_av$bacteria))
# 
# df_pvalue<-matrix(0, length(unique(MIC_mod_av$bacteria)) , 12)
#   
# row=1
# for (i in 1:(length(unique(MIC_mod_av$bacteria)))) { #vertical 
#   
#   df_pvalue[i,1]<-bact[i]
#   
#   MIC_mod_av %>%
#   subset(bacteria %in% bact[i])->sub
# 
#      for(j in 4:14){#horizontal 
#        
#        control<-setNames(sub[c(row:(row+2)), c(3)], c("control"))
#        test<-setNames(sub[c(row:(row+2)), c(j)], c("test"))
#        # print(test)
#        
#      cbind(control, test)->mydata
#      
#      mydata%>%
#        gather( group, OD, "control":"test") %>%
#        t_test( OD ~ group, alternative = "greater") -> res
# 
#        
#        
#        df_pvalue[i,c(j-2)]<-(res$p)
#        
#        
#      }
#   df_pvalue[i, 1]<-bact[i]
#   }
# 
# 
# 
# 
# 
# df_pvalue_MBC<-matrix(0, length(unique(MBC_mod_av$bacteria)) , 12)
#   
# row=1
# for (i in 1:(length(unique(MBC_mod_av$bacteria)))) { #vertical 
#   
#   df_pvalue_MBC[i,1]<-bact[i]
#   
#   MBC_mod_av %>%
#   subset(bacteria %in% bact[i])->sub
# 
#      for(j in 4:14){#horizontal 
#        
#        control<-setNames(sub[c(row:(row+2)), c(3)], c("control"))
#        test<-setNames(sub[c(row:(row+2)), c(j)], c("test"))
#        # print(test)
#        
#      cbind(control, test)->mydata
#      
#      mydata%>%
#        gather( group, OD, "control":"test") %>%
#        t_test( OD ~ group, alternative = "greater") -> res
# 
#        
#        
#        df_pvalue_MBC[i,c(j-2)]<-(res$p)
#        
#        
#      }
#   df_pvalue_MBC[i, 1]<-bact[i]
#   }
# 
# 
# df_pvalue<-setNames(as.data.frame(df_pvalue), c("bacteria", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
# df_pvalue_MBC<-setNames(as.data.frame(df_pvalue_MBC), c("bacteria", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
# 
# df_pvalue_MBC$assay<-"MBC"
# df_pvalue$assay<-"MIC"
# 
# df_pvalue_both<-rbind(df_pvalue, df_pvalue_MBC)
# 
```
 



