---
title: "H2O2 and O2 correlations"
output: html_document
date: '2022-12-15'
---


```{r setup, echo =FALSE}
.libPaths('C:\\Users\\zuendj\\Documents\\R4Libs')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/zuendj/Desktop/03_data R/oxidative stress", cho = TRUE, warning = FALSE, message = FALSE)

# Install Packages:
# install.packages("rlang")
# install.packages("tidyr")
# install.packages("ggbreak")
# install.packages("caret")
library(caret)

library(tidyverse)
library(ggplot2)
library(tidyr)
# install.packages("devtools")
# devtools::install_github("slowkow/ggrepel")
library(ggrepel)
library(ggbreak)
library(openxlsx)
```

# 1. Load the data and calculate median MIC & MBC
```{r}
h2o2 = read.csv(file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_MBC_H2O2.csv", sep=",", header=T, check.names =F)
names(h2o2)[2]<-"bacteria"
o2 = read.csv(file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/MIC_MBC_O2.csv", sep=",", header=T, check.names =F)


median_h2o2 <- aggregate(h2o2$value_H2O2, list(h2o2$condition_H2O2, h2o2$bacteria), FUN=median)
names(median_h2o2)[1]<-"assay"
names(median_h2o2)[2]<-"bacteria"
names(median_h2o2)[3]<-"value_h2o2"

h2o2_wide<-pivot_wider(median_h2o2, names_from = assay, values_from = value_h2o2, values_fill = NA)



median_o2 <- aggregate(o2$value_O2, list(o2$condition_O2, o2$bacteria), FUN=median)
names(median_o2)[1]<-"assay"
names(median_o2)[2]<-"bacteria"
names(median_o2)[3]<-"value_o2"

o2_wide<-pivot_wider(median_o2, names_from = assay, values_from = value_o2, values_fill = NA)
names(o2_wide)<-c("bacteria", "MBC oxygen", "MIC oxygen")
names(h2o2_wide)<-c("bacteria", "MBC h2o2", "MIC h2o2")

joined_mics<-as.data.frame(left_join(o2_wide, h2o2_wide))
rownames(joined_mics)<-joined_mics[,1]

```

```{r}
coverage = read.csv(file = "C:/Users/zuendj/Desktop/03_data R/oxidative stress/input/final_coverage.csv", sep=";", header=T, check.names =F)
names(coverage)[2]<-"bacteria"

```


```{r}
coverage<-coverage[,-1]

coverage%>%
  group_by(bacteria)%>%
  summarize_all(mean)%>%
  as.data.frame()->coverage_mean
rownames(coverage_mean)<-coverage_mean[,1]
coverage_mean<-coverage_mean[,-1]

mean_matrix<-as.matrix(coverage_mean)

```

```{r}
jpeg("C:/Users/zuendj/Desktop/03_data R/oxidative stress/output/defense.jpeg", width=1000, height=1000)

heatmap.2(mean_matrix, # data frame a matrix
          marg = c(30,20),
          density.info = "none", # Remove density legend lines
          trace = "none",
          # dendrogram = "row", 
           colsep=1:nrow(h2o2matrix), # Add vertical grid lines
          rowsep=1:nrow(h2o2matrix), # Add horizontal grid lines
          sepcolor = "black",
          col = viridis::viridis_pal(),
          cexRow = 1.5,
          cexCol = 1.5,
          lwid=c(1, 10),
          lhei = c(1,10), key=T, keysize = 5)

dev.off()

```

# 2. correlation MBC O2 & SOD
```{r}
coverage_o2<-merge(coverage_mean, joined_mics[,-1], by ="row.names")
row.names(coverage_o2)<-coverage_o2$Row.names

coverage_o2[, c("MBC oxygen", "MIC oxygen","MBC h2o2", "MIC h2o2" )]<-log2(coverage_o2[, c("MBC oxygen", "MIC oxygen","MBC h2o2", "MIC h2o2")])
                                                                                       
                                                                                       
coverage_o2$`MIC oxygen`<-(coverage_o2$`MIC oxygen`-min(coverage_o2$`MIC oxygen`))/(max(coverage_o2$`MIC oxygen`)-min(coverage_o2$`MIC oxygen`))
coverage_o2$`MIC h2o2`<-(coverage_o2$`MIC h2o2`-min(coverage_o2$`MIC h2o2`))/(max(coverage_o2$`MIC h2o2`)-min(coverage_o2$`MIC h2o2`))
coverage_o2$`MBC oxygen`<-(coverage_o2$`MBC oxygen`-min(coverage_o2$`MBC oxygen`))/(max(coverage_o2$`MBC oxygen`)-min(coverage_o2$`MBC oxygen`))
coverage_o2$`MBC h2o2`<-(coverage_o2$`MBC h2o2`-min(coverage_o2$`MBC h2o2`))/(max(coverage_o2$`MBC h2o2`)-min(coverage_o2$`MBC h2o2`))
```

```{r}
o2matrix<-as.matrix(coverage_o2[,-c(1, 31, 32, 33, 34)])

vec <- c(rep("green", 29), rep("red", 4))



jpeg("C:/Users/zuendj/Desktop/03_data R/oxidative stress/output/heat_mbc_h2o2.jpeg", width=1000, height=1000)


heatmap.2(as.matrix(coverage_o2[,-c(1)]), # data frame a matrix
          marg = c(27,20),
          density.info = "none", # Remove density legend lines
          trace = "none",
          # dendrogram = "row",
          colsep=1:ncol(coverage_o2[,-c(1)]), # Add vertical grid lines
          rowsep=1:nrow(coverage_o2[,-c(1)]), # Add horizontal grid lines
          sepcolor = "darkgrey",
          col = viridis::viridis_pal(),
          cexRow = 1.5,
          cexCol = 1.5,
          lwid=c(3, 20),
          lhei = c(2,20), key=T, keysize =1,
          ColSideColors = vec
         )

legend("bottomright",
       legend=c("in silico", "in vitro tolerance"), 
       fill=c("green", "red"))




dev.off()


```

```{r}

```


