---
title: "Relative metabolites H2O2"
output: html_document
date: '2022-12-29'
---
```{r setup, echo =FALSE}
.libPaths('C:\\Users\\zuendj\\Documents\\R4Libs')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/zuendj/Desktop/03_data R/oxidative stress", cho = TRUE, warning = FALSE, message = FALSE)

# Install Packages:
# install.packages("rlang")
# install.packages("tidyr")
# install.packages("ggbreak")

# library(ggpmisc)
# library(tidyverse)
# library(ggplot2)
# library(tidyr)
# install.packages("devtools")
# devtools::install_github("slowkow/ggrepel")
# library(ggrepel)
# library(ggbreak)
# library(openxlsx)
# library(readxl)
# library(ggh4x)
# library(ggpubr)
# library(ggpubr)
# library(rstatix)
# library(ggnewscale)

```

# 1. Read all the data into one df
```{r}
setwd("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/02_hplc_pure/02_H2O2/01_import")
hplc_raw <- read.xlsx("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/02_hplc_pure/02_H2O2/01_import/Final_import.xlsx")
```


```{r}
order <- c(
  "Blautia obeum",
  "Faecalibacterium duncaniae",
  "Roseburia faecis",
  "Faecalibacterium prausnitzii",
  "Agathobacter rectalis",
  "Anaerotignum lactatifermentans",
  "Blautia hydrogenotrophica",
  "Butyricicoccus pullicaecorum",
  "Clostridium sporogenes",
  "Dorea longicatena",
  "Fusicatenibacter saccharivorans",
  "Lachnospira eligens",
  "Mediterraneibacter gnavus",
  "Roseburia intestinalis",
  "Segatella copri",
  "Enterocloster aldenensis",
  "Anaerostipes hadrus",
  "Bacteroides cellulosilyticus",
  "Bacteroides fragilis",
  "Blautia hansenii",
  "Blautia producta",
  "Parabacteroides merdae",
  "Anaerostipes caccae",
  "Bacteroides intestinalis",
  "Bacteroides thetaiotaomicron",
  "Bacteroides uniformis",
  "Bacteroides xylanisolvens",
  "Phocaeicola dorei",
  "Bacteroides caccae",
  "Bacteroides faecis",
  "Bacteroides ovatus",
  "Bifidobacterium adolescentis",
  "Bifidobacterium longum",
  "Collinsella aerofaciens",
  "Eubacterium limosum",
  "Parabacteroides distasonis",
  "Phascolarctobacterium faecium",
  "Phocaeicola vulgatus",
  "Enterococcus faecalis",
  "Escherichia coli",
  "Lactiplantibacillus plantarum")

```

```{r}

hplc_raw%>%
  subset(!condition %in% c("blank", "blank "))->subset


subset<-subset[, c("rep","assay","remove_for_data_analysis", "condition","Succinat_[mM]", "Lactat_[mM]", "Formiat_[mM]", "Acetat_[mM]", "Butyrat_[mM]",  "Succinate", "Lactate", "Formate", "Acetate", "Propionate", "Butyrate")]

```


# 2. Calculate relative values
```{r}
#define new df for relative values
HPLC_wide_h2o2 <- subset
#calculate relative values; first calculate total SCFA

##values have to be numeric
numeric_columns <- c("Succinate", "Lactate", "Formate", "Acetate", "Propionate", "Butyrate")
HPLC_wide_h2o2[, numeric_columns] <- sapply(HPLC_wide_h2o2[, numeric_columns], as.numeric)


#calculate relative values; first calculate total SCFA
HPLC_wide_h2o2$total_C<-NA


scfas<-c("succinate", "lactate" , "formate", "acetate","propionate","butyrate")
scfas_rel<-paste0(scfas, "_rel_mM")
scfas_rel_C<-paste0(scfas, "_rel_C")
number_c <- c(4, 3, 1, 2, 3, 4) #nuber of c atoms for each organic acid

###calculate the relative values based on mM
for (i in 1:nrow(HPLC_wide_h2o2)){
  x<-HPLC_wide_h2o2[i,c(numeric_columns)]
  HPLC_wide_h2o2[i,c("total_mM")]<-  sum(x[which(x>0)])
  
  for (j in 1:length(scfas)){
    HPLC_wide_h2o2[i,scfas_rel[j]] = HPLC_wide_h2o2[i,numeric_columns[j]] / HPLC_wide_h2o2[i, c("total_mM")]
  }
}

## calculate the relative values based in total C
for (i in 1:nrow(HPLC_wide_h2o2)){
  vec<-c(HPLC_wide_h2o2[i,c("Lactate")]*3,
         HPLC_wide_h2o2[i,c("Formate")]*1,
         HPLC_wide_h2o2[i,c("Succinate")]*4,
         HPLC_wide_h2o2[i,c("Butyrate")]*4,
         HPLC_wide_h2o2[i,c("Propionate")]*3,
         HPLC_wide_h2o2[i,c("Acetate")]*2)
  HPLC_wide_h2o2[i,c("total_C")]<-  sum(vec[which(vec>0 )])
  
  for (j in 1:length(scfas)){
    HPLC_wide_h2o2[i,scfas_rel_C[j]] = HPLC_wide_h2o2[i,numeric_columns[j]]*number_c[j]/ HPLC_wide_h2o2[i, c("total_C")]
  }
}

HPLC_wide_h2o2%>%
  mutate(total_mM = ifelse(total_mM == 0, NA, total_mM))->HPLC_wide_h2o2_NA

```

```{r}

  
HPLC_wide_h2o2_NA[, c("assay","condition","butyrate_rel_mM", "propionate_rel_mM","acetate_rel_mM", "formate_rel_mM" , "lactate_rel_mM", "succinate_rel_mM" )]  %>%
  subset(condition %in% "control")%>%
  gather(metabolite, rel_conc, "butyrate_rel_mM":"succinate_rel_mM")->controls
  
setNames(aggregate(controls$rel_conc, by=list(controls$metabolite, controls$assay), FUN=mean, na.rm =T), c("metabolite", "bacteria", "rel_conc"))->means_controls

  
 
```

```{r}
# unloadNamespace("ggnewscale")
#  devtools::install_github("eliocamp/ggnewscale@v0.4.3")
#  library(ggnewscale)


means_controls%>%
  left_join(., 
            read.xlsx("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/00_experimentation/01_pure_culture/20240207_Strain_panel_metabol.xlsx")[, c("bacteria", "Phylum", "Genus")])->phylogeny

rbind(phylogeny%>%
        mutate(type= "metabol"), 
      phylogeny %>%
        mutate(metabolite = "b_Genus",
               type="b_Genus"))%>%
  rbind(., phylogeny %>%
        mutate(metabolite = "a_Phylum",
               type="a_Phylo"))%>%
  filter(rel_conc > 0)%>%  
  mutate(bacteria = ifelse(bacteria == "Prevotella copri", "Segatella copri", bacteria))%>%
  mutate(bacteria = ifelse(bacteria == "Ruminococcus gnavus", "Mediterraneibacter gnavus", bacteria))%>%
   mutate(Genus = ifelse(bacteria ==  "Segatella copri", "Segatella", Genus))%>%
  mutate(Genus = ifelse(bacteria ==  "Mediterraneibacter gnavus", "Mediterraneibacter",  Genus))%>%
  mutate(Genus = factor(Genus))%>%
  mutate(metabolite = factor(metabolite, levels= c("a_Phylum",   "b_Genus", "acetate_rel_mM", "butyrate_rel_mM", "formate_rel_mM" ,"lactate_rel_mM", "propionate_rel_mM" ,"succinate_rel_mM")))%>%  
   mutate(bacteria = factor(bacteria))->sub




  
 sub%>%
   subset( metabolite %in% c("b_Genus", "succinate_rel_mM", "lactate_rel_mM", "formate_rel_mM", "butyrate_rel_mM", "propionate_rel_mM" ,"acetate_rel_mM"))%>%
  ggplot(aes(y=bacteria, x=metabolite))+
   
  #  geom_tile(data = subset(sub, metabolite %in% c("a_Phylum")), aes(fill = Phylum )) +
  #  scale_fill_manual(values = c(  "#a6cee3","indianred","cyan4","pink3"))+
  # guides(fill = guide_legend(nrow = 4))+

    geom_tile(data = subset(sub, metabolite %in% c("b_Genus")), aes(fill = Genus )) +
   scale_fill_manual(values=c("#1f78b4","#a6cee3", "#80b1d3","#8dd3c7","#33a02c", "pink3","#e31a1c", "#ff7f00",   "#fb9a99",  "#6a3d9a", "#cab2d6","#fdbf6f", "darkgoldenrod2", "#b15928",  "#fb8072", "#5c342c", "#b36966", "#A8AF51" , "#484939", "#CE6C4E", "#E6BAAC",  "#B1A7CD", "darksalmon", "lightgreen"))+ 
  new_scale_fill() +
   geom_tile(data = subset(sub, metabolite %in% c("succinate_rel_mM", "lactate_rel_mM", "formate_rel_mM", "butyrate_rel_mM", "propionate_rel_mM" ,"acetate_rel_mM")),
                aes(fill = rel_conc )) +
   scale_fill_gradientn(colors = c( "white", "black"),  na.value= "white",  limits=c(0, 1), breaks = c(0, 0.5, 1), name= "Fraction")+
  

  
   
  facet_grid(rows=vars(Phylum), cols=vars(type), scales="free", space = "free")+
  theme(text= element_text(size=15),
        strip.text = element_blank(),
        axis.title = element_blank(),
        axis.text.y=element_text(face="italic", size=10),
        axis.ticks = element_blank(),
        panel.border=element_rect(fill=NA), 
        panel.background = element_rect(fill="white"),
        rect = element_rect(fill = "transparent"),
        legend.text.align = 0, 
        panel.spacing = unit(0, "lines"),
        axis.text.x = element_text(angle=90, hjust=1, vjust=0.5),
        legend.title =   element_text(size=15),
        # legend.key.height  = unit(0.5, 'cm'),legend.key.width  = unit(0.5, 'cm') , 
        legend.position = "bottom",
        legend.text = element_text(face="italic"))+
  
  scale_x_discrete(labels = c('b_Genus' = 'Genus', 'a_Phylum' = 'Phylum',"succinate_rel_mM" = "Succinate", "lactate_rel_mM"="Lactate", "formate_rel_mM"="Formate", "butyrate_rel_mM"="Butyrate", "propionate_rel_mM" = "Propionate" ,"acetate_rel_mM"="Acetate"))


ggsave(filename = "species_panel..png",   
         path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final",
       device = "png", bg= "transparent", 
         width =35,
         height = 20,
         units = c("cm"))


```


# Test statistical differences in total metabolites
```{r}
# library(ggpubr)
left_join(setNames(aggregate(HPLC_wide_h2o2_NA$total_mM, by=list(HPLC_wide_h2o2_NA$condition,  HPLC_wide_h2o2_NA$assay), FUN=sd, na.rm=T), c("condition",  "assay", "sd")),
setNames(aggregate(HPLC_wide_h2o2_NA$total_mM, by=list(HPLC_wide_h2o2_NA$condition,  HPLC_wide_h2o2_NA$assay), FUN=mean, na.rm=T), c("condition",  "assay", "mean"))) %>%
  mutate(assay = ifelse(assay == "Prevotella copri", "Segatella copri", assay))%>%
  mutate(assay = ifelse(assay == "Ruminococcus gnavus", "Mediterraneibacter gnavus", assay))->mean_h2o2


#get the MBC tolerance to order the plot - add 1 to the faculative anaerobes so that they are in the bottom row
order_h2o2<- read.xlsx("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/01_OD_pure/02_H2O2/H2O2_tolerances.xlsx")

#t test
HPLC_wide_h2o2[, c("assay", "condition", "total_mM", "remove_for_data_analysis")]%>%
   mutate(assay = ifelse(assay == "Prevotella copri", "Segatella copri", assay))%>%
  mutate(assay = ifelse(assay == "Ruminococcus gnavus", "Mediterraneibacter gnavus", assay))%>%
  subset(condition %in% c("control",  "NIC"))%>%
  subset(!assay %in% c("blank", "blank "))%>%
   mutate(assay = factor(assay, levels=order))%>%
  group_by(assay)%>%
  t_test(total_mM ~ condition, ref.group = "control")%>%
  add_significance()%>%
  add_xy_position(x="condition")->stats




mean_h2o2%>%
  subset(!assay %in% c("blank", "blank "))%>%
  mutate(assay = factor(assay, levels=order))%>%
  subset(condition %in% c("control",  "NIC"))%>%
  mutate(condition = ifelse(condition =="NIC", "a_NIC", condition))%>%
  # mutate(condition = factor(condition), levels=c( "NIC", "control"))%>%
  ggplot(aes(y=mean, x=condition))+
  geom_col(aes(fill=condition, position = condition), position = position_dodge(0.8), width=0.7)+
  geom_errorbar(aes(ymin=mean - sd, ymax=mean +sd, group=condition), width=.7, position=position_dodge(.9) )+
  stat_pvalue_manual(stats, label="p.signif", coord.flip = TRUE, vjust=0.5, hide.ns = T,  y.position=50, step.increase = 0.1)+
  facet_grid(rows=vars(assay), scales = "free")+
  coord_flip()+
  theme(text =element_text(size=15),
        strip.text.y = element_text(angle=0))+
  ylab("Total [mM]")+
  scale_x_discrete(labels=c("a_NIC"="Stress", "control" = "Control"))+
  scale_fill_manual(values=c("cyan4", "indianred" ), labels=c("Control", "Stress"))-> total_C_h2o2


total_C_h2o2

ggsave(filename = paste( "h2o2_pure cult_tot..jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/metabolites",
       width = 20,
       height = 40,
       units = c("cm"))

```


# 6. Perform T test & Shapiro Wilk test to check for normality

```{r}
#transform into long
HPLC_h2o2_long <-  gather(HPLC_wide_h2o2, metabolite, concentration, "succinate_rel_mM":"butyrate_rel_mM", factor_key = T ) 
```


```{r}

# stats<-as.data.frame(matrix(0,0,5))
# names(stats)<-c("condition_agar", "metabolite", "p", "p.signif", "Bacteria")

stats_h2o2<-matrix(0,0,5)
stats_h2o2_shapi<-matrix(0,0,5)
bacteria_names<- unique(HPLC_h2o2_long$assay)
metabol<- unique(HPLC_h2o2_long$metabolite)


wil<-"init"
out<-"init"
shapi_out<-"init"
shapi<-"init"



##filter out samples with no growth
HPLC_h2o2_long%>%
  subset(total_mM >1)%>% #remove first col
  filter(!is.na(concentration))->HPLC_h2o2_long #get only teh metabolites that are actually produced

#loop for plots for all bacteria
for (i in 1:length(bacteria_names)) {
##create subset
  subset(HPLC_h2o2_long, assay == bacteria_names[i])->bacteria_subset
  #get the metabolites that are produced as a vector to loop over
  metabol<-unique(bacteria_subset$metabolite)
  
  for (j in 1:length(metabol)){
     subset(bacteria_subset, metabolite == metabol[j])->metabol_subset
    

#remove all df taht contain results
rm(wil) 
rm(out)
rm(shapi_out)
rm(shapi)

#do t test - try() to avoid interruption of loop in case t test cannot be performed (for zero value sor so) 
try(
  metabol_subset %>%
  t_test(data= .,
  formula = concentration ~ condition, ref.group = 
    "control")%>%
  add_significance()%>% 
  add_xy_position(x="metabolite") -> wil
  , 
  silent = T)
    
    
try(wil$Bacteria<- bacteria_names[i], silent=T)
try(wil$agar_condition<- cond[x], silent=T)
try(wil$metabolite<- metabol[j], silent=T)
try(out<-wil[, c( "metabolite",  "p.adj.signif", "Bacteria", "group2")], silent=T)

# do shapiro tets for the anaerobic and aerobic samples individually

    #get the agar conditions
   cond<-unique(metabol_subset$condition) 
    #loop over the agar conditions to create the final subset to bet tested
    for (z in 1:length(cond)){


try(
  metabol_subset%>%
    subset(condition %in% cond[z])%>%
     shapiro_test(concentration) -> shapi_out
  , silent = T)
  
try(shapi<-shapi_out[, c("p")], silent=T)
try(shapi$Bacteria<- bacteria_names[i], silent=T)
try(shapi$metabolite<- metabol[j], silent=T)
try(shapi$condition<- cond[z], silent=T)
try(stats_h2o2_shapi<-rbind(stats_h2o2_shapi, shapi), silent=T)}
   
try(stats_h2o2<-rbind(stats_h2o2, out), silent=T)

  }}

# stats_h2o2_shapi%>%
#   filter(p<0.05)



#to match the formate, pivot wider shapiro
shapiro_wide_h2o2<-setNames(pivot_wider(stats_h2o2_shapi, values_from = p, names_from = condition), c( "Bacteria", "metabolite", "p_shapiro_control", "NIC-1", "NIC"))%>%
  gather(condition, p_shapi, "NIC-1":"NIC")

left_join(setNames(stats_h2o2, c("metabolite", "p.adj.signif", "Bacteria", "condition")), shapiro_wide_h2o2)->stats_all_h2o2
```



## Merge mean values with statistics

```{r}
stats_all_h2o2$p_corrected<-stats_all_h2o2$p.adj.signif



for (i in 1:nrow(stats_all_h2o2)){

  
    if ( stats_all_h2o2[i,c("p_shapi")] < 0.05 | is.na(stats_all_h2o2[i,c("p_shapi")]) ){
    stats_all_h2o2[i,c("p_corrected")] ="ns"}
  
   if ( stats_all_h2o2[i,c("p_shapiro_control")] < 0.05 | is.na(stats_all_h2o2[i,c("p_shapiro_control")]) ){
    stats_all_h2o2[i,c("p_corrected")] ="ns"}
  
  # if (is.na(means_stats_h2o2[i, c("p")])== TRUE){
  # means_stats_h2o2[i,c("p_corrected")] ="ns"}
}

```

# 4. Calculate means & SD 
```{r}

# HPLC_h2o2_long%>%
#   subset(!remove_for_data_analysis %in% "yes")->HPLC_h2o2_long

left_join(
  setNames(aggregate(HPLC_h2o2_long$concentration, list(HPLC_h2o2_long$assay, HPLC_h2o2_long$metabolite, HPLC_h2o2_long$condition), FUN=mean, na.rm=T), c("Bacteria", "metabolite", "condition", "mean")),
setNames(aggregate(HPLC_h2o2_long$concentration, list(HPLC_h2o2_long$assay, HPLC_h2o2_long$metabolite, HPLC_h2o2_long$condition), FUN=sd, na.rm=T),
         c("Bacteria", "metabolite", "condition" ,"sd")))->means_h2o2

means_h2o2[,c("Bacteria", "metabolite", "condition", "mean")]%>%
  pivot_wider(names_from = condition, values_from = c(mean))%>%
  setNames(c("Bacteria", "metabolite", "mean_control", "mean_NIC", "mean_NIC_1"))->means_wide_h2o2

```

```{r}
means_wide_h2o2%>%
  
  mutate(NIC = mean_NIC - mean_control)%>%
  mutate(NIC_1 = `mean_NIC_1` - mean_control)%>%
  gather(condition, ratio, "NIC":"NIC_1")%>%
  mutate(mean_control = NULL,
        mean_NIC = NULL,
        mean_NIC_1 = NULL)%>%
  left_join(stats_all_h2o2)->ratio_h2o2

```


# 4. Calculate means of absolute values: to filter for metabolites that are of low concentration
```{r}

HPLC_wide_h2o2%>%
  gather(metabolite, concentration, "Succinate": "Butyrate")%>%
  mutate(concentration = as.numeric(concentration))->abs_long


setNames(aggregate(abs_long$concentration, list(abs_long$assay,  abs_long$metabolite, abs_long$condition), FUN=mean, na.rm=T), c("Bacteria", "metabolite", "condition", "mean_conc"))%>%
  pivot_wider(names_from = condition, values_from = mean_conc)%>%
  setNames(c("Bacteria",   "metabolite","mean_conc_control", "NIC", "NIC_1"))%>%
  gather(condition, mean_abs, "NIC":"NIC_1")%>%
  mutate(metabolite = ifelse(metabolite == "Acetate", "acetate_rel_mM", metabolite))%>%
  mutate(metabolite = ifelse(metabolite == "Butyrate", "butyrate_rel_mM", metabolite))%>%
  mutate(metabolite = ifelse(metabolite == "Propionate", "propionate_rel_mM", metabolite))%>%
  mutate(metabolite = ifelse(metabolite == "Succinate", "succinate_rel_mM", metabolite))%>%
  mutate(metabolite = ifelse(metabolite == "Lactate", "lactate_rel_mM", metabolite))%>%
   mutate(metabolite = ifelse(metabolite == "Formate", "formate_rel_mM", metabolite))->means_absolute_h2O2 #machtch names of metabolites with ratio_O2 to perform left_join

```


```{r}
unique(ratio_h2o2$metabolite)

stats_absolute_h2o2<-left_join(ratio_h2o2, means_absolute_h2O2)%>%
   mutate(p_corrected = ifelse(is.na(p_corrected), "ns", p_corrected))%>%
  mutate(mean_conc_control = ifelse(is.na(mean_conc_control), 0, mean_conc_control))%>%
  mutate(mean_abs = ifelse(is.na(mean_abs), 0, mean_abs))

stats_absolute_h2o2$p_corrected_low_conc<-stats_absolute_h2o2$p_corrected

for (i in 1:nrow(stats_absolute_h2o2)){
  if (!is.na(stats_absolute_h2o2[i,"mean_conc_control"]) == T && 
      
      !is.na(stats_absolute_h2o2[i,"mean_abs"]) == T &&
      
      ((stats_absolute_h2o2[i,"mean_conc_control"] > -1 && 
        stats_absolute_h2o2[i,"mean_conc_control"] <= 0 && 
        stats_absolute_h2o2[i,"mean_abs"] > -1 && 
        stats_absolute_h2o2[i,"mean_abs"] <= 0) 
      || 
       (stats_absolute_h2o2[i,"mean_conc_control"] >= 0 && 
        stats_absolute_h2o2[i,"mean_conc_control"] < 1 &&
        stats_absolute_h2o2[i,"mean_abs"] >= 0 && 
        stats_absolute_h2o2[i,"mean_abs"] < 1))  || 
      
       (stats_absolute_h2o2[i,"mean_conc_control"] <= 0 && 
        stats_absolute_h2o2[i,"mean_conc_control"] > -1 &&
        stats_absolute_h2o2[i,"mean_abs"] >= 0 && 
        stats_absolute_h2o2[i,"mean_abs"] < 1)
       || 
       (stats_absolute_h2o2[i,"mean_conc_control"] >= 0 && 
        stats_absolute_h2o2[i,"mean_conc_control"] < 1 &&
        stats_absolute_h2o2[i,"mean_abs"] >= 0 && 
        stats_absolute_h2o2[i,"mean_abs"] >  -1))

       {
   stats_absolute_h2o2[i,"p_corrected_low_conc"] = "ns"
  }
}


```




```{r}
# taxonomy = read.csv(file = "P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/Strain_panel.csv", sep=";", header=T, check.names =F)
# colnames(taxonomy)[colnames(taxonomy) == "bacteria"] <- "Bacteria"
# 
# tax<-left_join(selection[, -c(15)], taxonomy)
```


```{r}
# library(scales)
stats_absolute_h2o2%>%
    subset(!is.na(ratio))%>%
   mutate(Bacteria = ifelse(Bacteria == "Prevotella copri", "Segatella copri", Bacteria))%>%
  mutate(Bacteria = ifelse(Bacteria == "Ruminococcus gnavus", "Mediterraneibacter gnavus", Bacteria))%>%
   
  subset(condition %in% c("control",  "NIC"))%>%
   mutate(Bacteria = factor(Bacteria, levels=order))%>%
  
  mutate(p_corrected_low_conc = ifelse(p_corrected_low_conc == "ns", "", p_corrected_low_conc))%>%
  mutate(metabolite = factor(metabolite, levels= c("succinate_rel_mM","lactate_rel_mM", "formate_rel_mM" ,"acetate_rel_mM","butyrate_rel_mM","propionate_rel_mM")))%>%
  mutate(ratio = ratio *100)->sub

min <- min(sub$ratio)
max <- max(sub$ratio)

sub%>%
  subset(p_corrected_low_conc = "*")

sub%>%
  subset(Bacteria %in% "Blautia hydrogenotrophica")

sub%>%
  ggplot(aes(x=metabolite, y=condition, fill=ratio))+
  geom_tile()+
  scale_fill_gradientn(colors = c( "coral", "white", "cyan4"),  na.value= "grey", values = rescale(c(-150, 0, 150)), limits=c(-150, 150), breaks=c(-100,0, 100))+
  facet_grid(rows=vars(Bacteria))+
    theme(text = element_text(size=10),
      strip.text.y = element_text(angle=0,  face="italic", hjust=0, size=8),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90,  vjust=0.5, hjust=1),
        axis.text.y = element_text( face="italic"), 
        panel.border=element_rect(fill=NA), 
        panel.background = element_rect(fill="white"),
        legend.text.align = 0, 
        strip.background = element_blank(),
        panel.spacing = unit(0, "lines"))+
  scale_x_discrete(labels=c("succinate_rel_mM"="Succinate",  "lactate_rel_mM" ="Lactate" ,  "formate_rel_mM"  ="Formate" , "acetate_rel_mM"  = "Acetate" , "propionate_rel_mM"="Propionate", "butyrate_rel_mM" = "Butyrate"))+
  labs(fill="Delta [%]")+
  geom_text(aes(label=p_corrected_low_conc))-> diff_metabol_h2o2

diff_metabol_h2o2

ggsave(filename = "O2_heatplot_selection_lowconc.jpeg",   
         path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/metabolites", 
         width = 22,
         height = 40,
         units = c("cm"))


```


```{r}
# library(cowplot)



plot_grid(          total_C_h2o2+theme(text=element_text(size=10),
                             legend.position = "none",
                             axis.title = element_blank(),
                                                         axis.ticks.y=element_blank(),
                             panel.border=element_rect(fill=NA), 
                             panel.background = element_rect(fill="white"),
                             legend.text.align = 0, 
                             strip.background = element_blank(),
                             panel.spacing = unit(0, "lines"), 
                          legend.title = element_blank(),
                           strip.text.y = element_blank())+ scale_fill_manual(values=c("cyan4", "indianred" )), 
          
          
          diff_metabol_h2o2+theme(text=element_text(size=10),
                                  legend.position = "none",
                                  axis.text.y = element_blank(),
                                   axis.text.x = element_text(),
                                  axis.ticks = element_blank()), 
          
          
        align= "h", rel_widths = c(0.7, 1), rel_heights = c(1,1), axis = 'tblr')

ggsave(filename = "metabolt_totalc..jpeg",   
         path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final", 
         width = 14,
         height = 23,
         units = c("cm"))
```





```{r}
plot_grid(
  #plot 1: growth
  growth_h2o2+ 
    theme(legend.position = "none",
          text=element_text(size=15),
          strip.text.y = element_blank(),
          plot.title = element_text(size=15))+
    ggtitle("Growth"), 
  #plot 2: metabol
  total_C_h2o2+
    theme(legend.position = "none", 
          plot.title = element_text(size=15),
          text=element_text(size=15),
          axis.text.y=element_blank(), 
          axis.title.y=element_blank(), 
          axis.ticks.y=element_blank(),
          strip.text.y = element_blank(), 
          panel.border=element_rect(fill=NA), 
          panel.background = element_rect(fill="white"),
          legend.text.align = 0, 
          strip.background = element_blank(),
          panel.spacing = unit(0, "lines"), 
          legend.text = element_blank())+
            ylab("Total C [mM]")+
            scale_fill_manual(values=c("cyan4", "indianred" ))+
    ggtitle("Total C"), 
  #plot3: total c
  diff_metabol_h2o2+
    theme(text=element_text(size=15),
            plot.title = element_text(size=15),
            legend.position = "none", 
          axis.text.y=element_blank(),
          strip.text.y = element_text(face="italic", hjust=0),
          axis.ticks = element_blank())+
    ggtitle("Individual metabolites"),
  ##define plot grid 
        align= "h", rel_heights = c(1,1,1), rel_widths=c(0.65,0.4, 1), nrow=1, axis = 'tblr')

ggsave(filename = "metabolt_totalc_h2O2.jpeg",   
         path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final", 
         width = 21,
         height = 30,
         units = c("cm"))
```


