```{r setup, echo =FALSE}
.libPaths('C:\\Users\\zuendj\\Documents\\R4Libs')
knitr::opts_chunk$set(echo = TRUE)

# Install Packages:
# install.packages("rlang")
# install.packages("tidyr")
# install.packages("ggbreak")

# library(ggpmisc)
 library(tidyverse)
# library(ggplot2)
# library(tidyr)
# install.packages("devtools")
# devtools::install_github("slowkow/ggrepel")
# library(ggrepel)
# library(ggbreak)
 library(openxlsx)
# library(readxl)
# library(ggh4x)
# library(ggpubr)
# library(ggpubr)
# library(rstatix)
library(ggnewscale)

```

# 1. Read all the data into one df
```{r}
# setwd("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/06_oxygen_measurements/unisense_O2_sensor/24_all_conditions")
o2 <- read.xlsx("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/06_oxygen_and_redox_measurements/unisense_O2_sensor/24_all_conditions/Measurements_all_jz.xlsx", sheet = "R_import")
```

```{r}
o2%>%gather(replicate, conc, "rep1":"rep2")%>%
  subset(volume_ml == 1)%>%
  mutate(well.nr = factor(well.nr, levels=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")))->gathered

setNames(aggregate(gathered$conc, by =list(gathered$time, gathered$`well.nr`), FUN=mean), c("time", "well.nr", "mg"))->mean

mean %>%
  rbind(., mean %>%
              subset(time ==1)%>%
              mutate(time =0)%>%
              mutate(mg=0))->mean_zero


gathered%>%
  left_join(., mean)%>%
  mutate(well.nr = factor(well.nr, levels=c("1", "4", "6" ,"9","12")))%>%
  subset(well.nr %in% c("1", "4","6" , "9", "12"))%>%
  ggplot(aes(x=time, y=conc))+
   # geom_line(aes(colour=agar, group=agar))+
  geom_line(aes(y=mg, colour=well.nr, group=well.nr))+
  ylab("mg/ml")+
  geom_point(aes(colour=well.nr), alpha=0.7, size = 3)+
  
  xlab("Time [h]") + ylab(expression(paste(O[2]~'[mg/ml]'))) +
  theme(text= element_text(size = 15), 
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA),
        strip.background = element_blank())+
  labs(colour="Agar")+
  scale_colour_manual(values=c("#a6cee3", "#b2df8a", "#fb9a99",  "#fdbf6f", "grey"), labels= c("0.15 %", "0.09 %", "0.07 %","0.04 %","0 %"))
  


ggsave(filename = "O2.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex",
       width =12,
       height = 10,
       units = c("cm"))   


# install.packages("DescTools")
# library(DescTools)


gathered%>%
  left_join(., mean)%>%
  mutate(time= factor(time, levels = c("1", "6", "24")))%>%
  ggplot(aes(x=well.nr, y=mg))+
   # geom_line(aes(colour=agar, group=agar))+
  geom_line(aes(colour=time, group=time))+
  ylab("mg/ml")+
  geom_point(aes(y=conc))
```

# h2o2
# 1. Read all the data into one df
```{r}
# setwd("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/06_oxygen_measurements/unisense_O2_sensor/24_all_conditions")
h2o2 <- read.xlsx("P:/Shared_documents/Janina_Zuend/08_phd/12_working_package_2/06_oxygen_and_redox_measurements/Redox_H2O2/redox_H2O2.xlsx")
```

```{r}
h2o2%>%
  mutate(conc = factor(conc, levels=c("7.3",  "2.3", "0.71","0.22", "0")))%>%
  # subset(well.nr %in% c("1", "4", "12"))%>%
  ggplot(aes(x=time, y=mV))+
   # geom_line(aes(colour=agar, group=agar))+
  geom_line(aes(y=mV, colour=conc, group=conc))+
  ylab("Redox potential [mV]")+
  geom_point(aes(colour=conc), alpha=0.7, size = 3)+
  
  xlab("Time [h]") +
  theme(text= element_text(size = 15), 
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA),
        strip.background = element_blank())+
  labs(colour=expression(H[2]*O[2]))+
  scale_colour_manual(values=c("grey", "#fdbf6f","#fb9a99", "#b2df8a","#a6cee3"   ), labels= c("7.3 mM", "2.3 mM", "0.71 mM","0.22 mM","0 mM"))
  


ggsave(filename = "H2O2.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex",
       width =12,
       height = 10,
       units = c("cm"))   
```


```{r}
result_matrix <- matrix(nrow=0, ncol=2)
levels<- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")

for (i in 1:12){
gathered%>%
  subset(well.nr %in% levels[i])->sub

  sub%>%ggplot(aes(y=conc, x=time))+
    geom_point()+
    geom_smooth(method="loess")->plot
  
  show(plot)
  
model<-loess(conc~time, data=sub)

mod.fun<-function(x) predict(model,newdata=x)
x<-integrate(mod.fun,1,24)

result <- c(levels[i], x$value)

result_matrix<- rbind(result_matrix, result)
}
```


```{r}
o2%>%gather(replicate, conc, "rep1":"rep2")%>%
  subset(volume_ml %in% c(2))->gathered

setNames(aggregate(gathered$conc, by =list(gathered$time, gathered$`agar.concentration`), FUN=mean), c("time", "agar", "mg"))->mean

mean %>%
  rbind(., mean %>%
              subset(time ==1)%>%
              mutate(time =0)%>%
              mutate(mg=0))->mean_zero

mean_zero%>%
  mutate(agar = round(agar, digits =3))%>%
  mutate(agar = factor(agar))%>%
  ggplot(aes(x=time, y=mg))+
  geom_line(aes(colour=agar, group=agar))+
  ylab("mg/ml")
  


ggsave(filename = "O2_2mL.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex",
       width =16,
       height = 16,
       units = c("cm"))   


# install.packages("DescTools")
# library(DescTools)



```

