```{r setup, echo =FALSE}
.libPaths('C:\\Users\\zuendj\\Documents\\R4Libs')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "P:/Shared_documents/Serafina Plüss/20230320_sequencing_results/Janina", cho = TRUE, warning = FALSE, message = FALSE)

# install.packages(
#   "microViz",
#   repos = c(davidbarnett = "https://david-barnett.r-universe.dev", getOption("repos"))
# )
# devtools::install_github("tidyverse/tidyverse")
#  library(tidyverse)
#  library(openxlsx)
#  library(ggh4x)
#  library(microViz)
# library(phyloseq)



```

```{r, echo =FALSE}
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
# source("https://raw.githubusercontent.com/fconstancias/metabaRpipe-source/master/Rscripts/functions.R")
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R")
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")

#get metadata file: load this function
sample.data.frame <- function(ps) {
  return(as(phyloseq::sample_data(ps), "data.frame"))}
```

## 1. Get the phyloseq object 
```{r}
# unloadNamespace("miaViz")
# unloadNamespace("mia")

phyloseq_rare <-readRDS("C:/Users/zuendj/Desktop/03_data R/wp2_complex/input/phyloseq_rare.RDS")
```

## export a list of top Genera in order to classify bzw. taxa with abundance >0.1 which is given by the filter)
```{r}
phyloseq_rare%>%
  physeq_glom_rename(taxrank = "Genus", 
                     speedyseq = T)%>%
   microbiome::transform("compositional") %>%
  subset_samples(time %in% c("pre-stress", "stress", "post_stress_1"))%>%
   psmelt()%>%
  subset(Abundance > 0.001)->df_abund

write.xlsx(setNames(as.data.frame(unique(df_abund$Genus)), c("Genus")), "C:/Users/zuendj/Desktop/03_data R/wp2_complex/aerotolerance_classification.xlsx" )
# 

```

```{r}

class<-read.xlsx("C:/Users/zuendj/Desktop/03_data R/wp2_complex/aerotolerance_classification_filtered.xlsx")

class$classification<-class$classification%>%
  replace_na("no classification")

df_abund_class <- left_join(df_abund, class[, c("Genus", "classification", "Literature")])
```


### Butyrate
##O2
```{r}
df_abund_class%>%
  subset(stress_level %in% c("max"))%>%
  subset(stress %in% c("O2") )%>%
  subset(time %in% c("stress", "post_stress_1"))%>%
   subset(Abundance > 0.001)%>%
  subset(Literature %in% "yes")->sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance")) %>%
  mutate(time = factor(time, levels =c("stress", "post_stress_1"))) %>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))  -> butyrate_producers
unique(butyrate_producers$time)

butyrate_producers%>%
  subset(time %in% "post_stress_1")%>%
  subset(incubation %in% "anaerobe")%>%
  shapiro_test(Abundance)

butyrate_producers%>%
  subset(!time %in% "pre-stress")%>%
  group_by(time)%>%
 wilcox_test(data= .,
  formula = Abundance ~ incubation   )%>%
  add_significance()%>%
  add_xy_position()%>%
  mutate(xmax = ifelse(time == "post_stress_1", 1.75, xmax),
         xmin = ifelse(time == "post_stress_1", 2.25, xmin))->stat_test


# %>%
#     mutate(xmax = ifelse(time == "stress", 2.2, xmax),
#          xmin = ifelse(time == "stress", 1.8, xmin))%>%



 left_join(setNames(aggregate(butyrate_producers$Abundance, by=list( butyrate_producers$stress_level, butyrate_producers$time, butyrate_producers$incubation), FUN= "mean"), c( "stress_level", "time", "incubation","mean")),  
           setNames(aggregate(butyrate_producers$Abundance, by=list( butyrate_producers$stress_level, butyrate_producers$time, butyrate_producers$incubation), FUN= "sd"), c( "stress_level", "time", "incubation","sd")))%>%
   mutate(mean = round(mean, digits=2))%>%
  mutate(sd = round(sd, digits=2))

butyrate_producers %>%
  # mutate(stress_level = factor(stress_level, levels =c("control","low", "median", "high", "max")))%>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))%>%
  ggplot(aes(x=time, y=Abundance))+
  geom_boxplot(aes(fill=incubation), outlier.shape = NA, position = position_dodge2(preserve = "single"), alpha=0.9)+
  geom_point(aes(colour=donor_name, group=incubation), position =position_jitterdodge(0.1), alpha=0.9)+
   facet_grid(cols=vars(stress_level))+
  theme(text = element_text(size  = 15),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(vjust=1, hjust=0),
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), 
        legend.text.align = 0,
        strip.background = element_rect(fill="white"),
        strip.text = element_blank())+
   scale_fill_manual(values=c( "skyblue3","lightpink3"), labels=c( "Control","Stress"), name="Condition")+
   stat_pvalue_manual(stat_test, label = "p.signif", hide.ns = T)+
  labs(colour="Donor", fill="Condition")+
  scale_x_discrete(labels=c(  "Stress", "Post-stress"))+
  ylab("Butyrate producers [%]")+
    scale_colour_manual(values=c("lightblue", "steelblue", "yellowgreen", "forestgreen", "lightpink1", "red3", "sienna1", "orange"), name="Donor")
  


ggsave(filename = paste( "Butyrate.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final",
       width = 10,
       height = 10,
       units = c("cm"))
```


```{r}
df_abund_class%>%
  subset(stress_level %in% c("max"))%>%
  subset(stress %in% c("O2"))%>%
   subset(Abundance > 0.001)%>%
  subset(Literature %in% "yes")->sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance")) %>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2"))) %>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))  -> butyrate_producers


sub%>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))%>%
  subset(time %in% "stress")%>%
  mutate(Abundance =Abundance *100)%>%
  mutate(OTU = reorder(OTU, Abundance))%>%
  ggplot(aes(x=incubation, y=Abundance))+
  geom_bar(aes(fill=OTU), stat = "identity")+
  theme(text = element_text(size  = 15),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
      
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA),
        # legend.position = "bottom",
        legend.text.align = 0, 
        strip.background = element_rect(fill= "white"),
         legend.key.height  = unit(0.5, 'cm'),legend.key.width  = unit(0.5, 'cm'))+
        
  labs(colour="Donor", fill="Condition")+
  ylab("Butyrate producers [%]")+
  facet_grid(cols=vars(donor_name))+
  scale_fill_manual(values=c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", 
                "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f", "#cab2d6", 
                "#ffff99", "#8ca252", "#b15928", "#377eb8"), name="Genus")+
  guides(fill = guide_legend( reverse = TRUE))+
  scale_x_discrete(labels=c("Control", "Stress"))


ggsave(filename = paste( "Butyrate_bar plots.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final",
       width = 17.5,
       height = 5,
       units = c("cm"))
```




### Butyrate
##H2O2
```{r}
df_abund_class%>%
  subset(stress %in% c("H2O2") | time %in% "pre-stress")%>%
   subset(Abundance > 0.001)%>%
  subset(Literature %in% "yes")->sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance")) %>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2")))   -> butyrate_producers


butyrate_producers%>%
  subset(!time %in% "pre-stress")%>%
  mutate(time = factor(time, levels=c("pre-stress", "stress", "post_stress_1")))%>%
   mutate(stress_level = factor(stress_level, levels =c("control","low", "median", "high")))%>%
  group_by(time)%>%
  t_test(data= .,
  formula = Abundance ~ stress_level, ref.group = "control" 
  )%>%
  add_significance()%>%
  add_xy_position()->stat_test
# 
# %>%
#     mutate(xmax = ifelse(time == "stress", 1.2, xmax),
#          xmin = ifelse(time == "stress", 0.8, xmin))%>%
#   mutate(xmax = ifelse(time == "post_stress_1", 1.8, xmax),
#          xmin = ifelse(time == "post_stress_1", 2.2, xmin))

 left_join(setNames(aggregate(butyrate_producers$Abundance, by=list( butyrate_producers$stress_level, butyrate_producers$time, butyrate_producers$incubation), FUN= "mean"), c( "stress_level", "time", "incubation","mean")),  
           setNames(aggregate(butyrate_producers$Abundance, by=list( butyrate_producers$stress_level, butyrate_producers$time, butyrate_producers$incubation), FUN= "sd"), c( "stress_level", "time", "incubation","sd")))

butyrate_producers %>%
   mutate(stress_level = factor(stress_level, levels =c("control","low", "median", "high")))%>%
  mutate(time = factor(time, levels=c("pre-stress", "stress", "post_stress_1")))%>%
  ggplot(aes(x=stress_level, y=Abundance))+
  geom_boxplot(aes(fill=incubation), outlier.shape = NA, position = position_dodge2(preserve = "single"), alpha=0.9)+
  geom_point(aes(colour=donor_name, group=incubation), position =position_jitterdodge(0.1), alpha=0.9)+
   facet_grid(cols=vars(time))+
  theme(text = element_text(size  = 15),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(vjust=1, hjust=0),
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), 
        legend.text.align = 0)+
   scale_fill_manual(values=c( "skyblue3","lightpink3"), labels=c( "Control","Stress"), name="Condition")+
   stat_pvalue_manual(stat_test, label = "p.adj.signif", hide.ns = T)+
  labs(colour="Donor", fill="Condition")+
  # scale_x_discrete(labels=c( "P1", "P2", "P3"))+
  ylab("Butyrate producers [%]")


ggsave(filename = paste( "Butyrate_h2o2.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final",
       width = 10,
       height = 7.5,
       units = c("cm"))
```


```{r}
df_abund_class%>%
  # subset(stress_level %in% c("max"))%>%
  subset(stress %in% c("O2"))%>%
   subset(Abundance > 0.001)%>%
  subset(Literature %in% "yes")->sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance")) %>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2"))) %>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))  -> butyrate_producers


sub%>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))%>%
  subset(time %in% "stress")%>%
  mutate(stress_level = factor(stress_level, levels=c("control", "low", "median", "high", "max")))%>%
  mutate(OTU = reorder(OTU, Abundance))%>%
  ggplot(aes(x=incubation, y=Abundance))+
  geom_bar(aes(fill=OTU), stat = "identity")+
  theme(text = element_text(size  = 15),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(vjust=1, hjust=0, size=10),
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), 
        legend.text.align = 0)+
  labs(colour="Donor", fill="Condition")+
  ylab("Butyrate producers [%]")+
  facet_grid(rows=vars(donor_name), cols=vars(stress_level), scales="free")+
  scale_fill_manual(values=c("#ffff99","#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", 
                "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f", "#cab2d6", "#377eb8", 
                 "#8ca252", "#b15928"))+
  guides(fill = guide_legend(reverse = TRUE))


ggsave(filename = paste( "Butyrate_bar plots.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/final",
       width = 20,
       height = 11,
       units = c("cm"))
```
```{r}
df_abund_class%>%
  # subset(stress_level %in% c("max"))%>%
  subset(stress %in% c("O2", "control"))%>% 
  subset(!time %in% "post_stress_2")%>%
  subset(Literature %in% "yes")%>%
   subset(Abundance > 0.001)->o2

o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "low")->low

o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "median")->median
o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "high")->high
o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "max")->max

o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "control", incubation = "aerobe")->ctrl_a

o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "low", incubation = "aerobe")->low_a

o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "median", incubation = "aerobe")->median_a
o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "high", incubation = "aerobe")->high_a
o2 %>%
  subset(time %in% "pre-stress")%>%
  mutate(stress_level = "max", incubation = "aerobe")->max_a

combined_df_control_o2 <- do.call(rbind, list(o2,  low, median, high, max, ctrl_a, low_a, median_a, high_a, max_a))
```


```{r}
combined_df_control_o2 -> sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance")) %>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1"))) %>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))  -> butyrate_producers


sub%>%
   mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1"))) %>%
  mutate(incubation = factor(incubation, levels =c("anaerobe","aerobe")))%>%
  subset(stress_level %in% "max")%>%
  mutate(OTU = reorder(OTU, Abundance))%>%
  ggplot(aes(x=time, y=Abundance))+
  geom_bar(aes(fill=OTU), stat = "identity")+
  theme(text = element_text(size  = 15),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(vjust=1, hjust=0, size=10),
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), 
        legend.text.align = 0)+
  labs(colour="Donor", fill="Condition")+
  ylab("Butyrate producers [%]")+
  facet_grid(rows=vars(donor_name), cols = vars(incubation, stress_level), scales="free")+
  scale_fill_manual(values=c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", 
                "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f", "#cab2d6", 
                "#ffff99", "#8ca252", "#b15928", "#377eb8", "indianred", "cyan4"))+
  guides(fill = guide_legend(reverse = TRUE))

ggsave(filename = paste( "oxygen.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 20,
       height = 20,
       units = c("cm"))

```



##O2
```{r}
combined_df_control_o2%>%
  subset(stress_level %in% "max")%>%
  # subset(stress %in% c("O2"))%>%
   subset(Abundance > 0)->sub


setNames(aggregate(sub$Abundance, by=list(sub$classification, sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("classification", "donor_name", "stress", "stress_level","incubation", "time", "Abundance"))%>%
  pivot_wider(names_from=incubation, values_from = Abundance)%>%
  mutate(diff = aerobe - anaerobe)%>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2")))  %>%    
  ggplot(aes(x=time, y=diff))+
  geom_boxplot(outlier.shape =  NA, position = position_dodge2(preserve = "single"))+
  geom_point(aes(colour=donor_name), position =position_jitterdodge(0.1))+
  # facet_grid(cols=vars(incubation))+
  theme(strip.text = element_text(size  = 20),
        axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=20, angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), legend.text.align = 0)+
   scale_fill_manual(values=c( "lightpink3","skyblue3"), labels=c( "Stress","Control"), name="Condition")+
  facet_grid(cols=vars(classification), rows=vars(stress_level), scales="free")

ggsave(filename = paste( "oxygen.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 30,
       height = 30,
       units = c("cm"))
```


##O2
```{r}
df_abund_class%>%
  subset(stress_level %in% "max")%>%
  subset(stress %in% c("O2"))%>%
   subset(Abundance > 0)->sub


setNames(aggregate(sub$Abundance, by=list(sub$classification, sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("classification", "donor_name", "stress", "stress_level","incubation", "time", "Abundance"))%>%
  pivot_wider(names_from=incubation, values_from = Abundance)%>%
  mutate(diff = aerobe - anaerobe)%>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2")))  %>%    
  ggplot(aes(x=time, y=diff))+
  geom_boxplot(outlier.shape =  NA, position = position_dodge2(preserve = "single"))+
  geom_point(aes(colour=donor_name), position =position_jitterdodge(0.1))+
  # facet_grid(cols=vars(incubation))+
  theme(strip.text = element_text(size  = 20),
        axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=20, angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), legend.text.align = 0)+
   scale_fill_manual(values=c( "lightpink3","skyblue3"), labels=c( "Stress","Control"), name="Condition")+
  facet_grid(cols=vars(classification), rows=vars(stress_level))

ggsave(filename = paste( "oxygen.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 30,
       height = 30,
       units = c("cm"))
```

```{r}
df_abund_class%>%
  subset(stress %in% c("O2") & 
           time %in% c("stress") & 
           incubation %in% c("aerobe"))%>%
  subset( classification %in% "microaerophile")->sub

aggregate(sub$Abundance, by=list(sub$Genus, sub$stress_level, sub$donor_name), FUN= mean)
```

```{r}
donor_cond<-c("D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8")

for (i in 1:length(donor_cond)){
df_abund_class%>%
  subset(stress %in% c("O2", "control") & donor_name %in% donor_cond[i] & time %in% "stress")->sub

setNames(aggregate(sub$Abundance, by=list(sub$classification, sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("classification", "donor_name", "stress", "stress_level","incubation", "time", "Abundance"))%>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2")), stress_level = factor(stress_level, levels=c("control", "low", "median", "high", "max")))  %>%     
  ggplot(aes(x=classification, y=Abundance))+
  geom_boxplot(outlier.shape =  NA, aes(fill=stress_level))+
  geom_point(aes(colour=stress_level, group=stress_level, shape = donor_name), position =position_jitterdodge(0.1))+
  # facet_grid(cols=vars(incubation))+
  theme(strip.text = element_text(size  = 20),
        axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=20, angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), legend.text.align = 0)+
   # scale_fill_manual(values=c( "lightpink3","skyblue3"), labels=c( "Stress","Control"), name="Condition")+
  facet_grid(cols=vars(incubation))


ggsave(filename = paste( donor_cond[i], "metabolites_controls.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 20,
       height = 15,
       units = c("cm"))
  


}
```

```{r}
df_abund_class%>%
  subset(stress %in% c("O2") & 
           time %in% c("stress") )%>%
  # subset( classification %in% c("microaerophile","facultative anaerobe"))%>%
  mutate(classification = ifelse(OTU == "Bacteroides", "Bacteroides", classification))%>%
   mutate(classification = ifelse(OTU == "Bifidobacterium", "Bifidobacterium", classification))%>%
  mutate(stress_level = factor(stress_level, levels=c("control", "low", "median", "high", "max")))%>%
  ggplot(aes(x=stress_level, y=Abundance))+
  geom_bar(stat="identity", aes(fill=classification))+
  facet_grid(cols=vars(incubation), rows=vars(donor_name))

ggsave(filename = paste("classification_bar.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 17,
       height = 15,
       units = c("cm"))
```

##H2O2
```{r}
af_abund_class%>%
  subset(stress %in% c("H2O2"))->sub

setNames(aggregate(sub$Abundance, by=list(sub$classification, sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("classification", "donor_name", "stress", "stress_level","incubation", "time", "Abundance"))%>%
  subset(stress %in% "H2O2")->sub

# aggregate(sub$Abundance, by=list(sub$donor_name), FUN="mean")->sub

sub[,  c("donor_name", "time", "stress_level", "stress", "Abundance", "incubation", "classification")]%>%
  subset(classification %in% c("anaerobic", "facultative anaerobe", "microaerophile"))%>%
  mutate(time = factor(time, levels=c("stress", "post_stress_1", "post_stress_2")))%>%
  mutate(stress_level = factor(stress_level, levels=c("control", "low", "median", "high")))%>%
  ggplot(aes(x=classification, y=Abundance))+
  geom_boxplot(aes(fill=stress_level), outlier.shape=NA)+
  geom_point(aes(colour=donor_name, group=stress_level), position=position_jitterdodge(0.1), size=2)+
  theme(axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=20, angle = 90, vjust= 0.5, hjust=1),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), legend.text.align = 0)+
  ylab("Abundance")+xlab("")+
  ggtitle("Metabolite production in passaged cultures")+
  labs(colour="Metabolite")+
  facet_grid(cols=vars(time))

af_abund_class[,  c("Genus","donor_name", "time", "stress_level", "stress", "Abundance", "incubation", "classification")]%>%
  subset(classification %in% c("facultative anaerobe"))%>%
  subset(stress_level %in% c("high") &
           time %in% "post_stress_2" &
           stress %in% "H2O2")%>%
  filter(Abundance > 0.005)->sub

unique(sub$Genus)

ggsave(filename = paste("classification_h2o2.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 20,
       height = 15,
       units = c("cm"))
```


```{r}
library(ggpmisc)
left_join(butyrate_producers, hplc)%>%
  ggplot(aes(x=Abundance, y=rel_butyrate))+
  geom_point()+
  stat_correlation(mapping = use_label(c("R")), size=8)+
  stat_poly_line(color="darkgrey") 
```




### Butyrate
##H2O2
```{r}
df_abund_class%>%
  subset(stress %in% c("H2O2"))%>%
   subset(Abundance > 0.001)%>%
  subset(Literature %in% "yes")->sub

setNames(aggregate(sub$Abundance, by=list(sub$donor_name, sub$stress, sub$stress_level, sub$incubation, sub$time), FUN="sum"), c("donor_name", "stress", "stress_level","incubation", "time", "Abundance"))%>%
  mutate(time = factor(time, levels =c("pre-stress","stress", "post_stress_1", "post_stress_2")))  %>%    
    mutate(stress_level = factor(stress_level, levels =c("control","low", "median", "high")))  %>% 
  ggplot(aes(x=time, y=Abundance))+
  geom_boxplot(outlier.shape =  NA, aes(fill=stress_level), position = position_dodge2(preserve = "single"))+
  geom_point(aes(colour=donor_name, group=stress_level, shape = stress_level), position =position_jitterdodge(0.1))+
  # facet_grid(cols=vars(incubation))+
  theme(strip.text = element_text(size  = 20),
        axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=20, angle=90, vjust=0.5, hjust=1),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), legend.text.align = 0)
   # scale_fill_manual(values=c( "lightpink3","skyblue3"), labels=c( "Stress","Control"), name="Condition")
ggsave(filename = paste( "Butyrate_h2O2.jpeg"),
       path = "C:/Users/zuendj/Desktop/03_data R/wp2_complex/output/classification",
       width = 30,
       height = 30,
       units = c("cm"))
```
